### ISSUE TITLE
swiftgen: command not found

### ISSUE THREAD

**Issue by PavelShar** [anilibria/anilibria-ios#1]
Доброго времени суток.
Решил собрать проект, но столкнулся со следующей проблемой.
 ```
/Users/paul/Library/Developer/Xcode/DerivedData/Anilibria-fhlaznhghgyyjievzdamxsdpqnxo/Build/Intermediates.noindex/Anilibria.build/Debug-iphoneos/Anilibria.build/Script-C7D4634022CC78CC00E763DF.sh: line 3: swiftgen: command not found
Command PhaseScriptExecution failed with a nonzero exit code
```

Проблема решилась следующим образом:
1. Добавил `SwiftGen` в `Podfile`
2. Заменил в `Build Phases` в 3 сверху скрипте `Run Script` c `swiftgen strings ` на `"$PODS_ROOT"/SwiftGen/bin/swiftgen strings`

После этих манипуляций проект собрался и установился.
Понятия не имею насколько это правильно, собираю проект в xcode первый раз в жизни.

os: Catalina 10.15.3
xcode: Version 11.6 (11E708)
device: iphone 11 pro

**Comment by Allui** [comment]
Привет.

[SwiftGen ](https://github.com/SwiftGen/SwiftGen) нужно ставить в систему через brew или mint. Лучше не добавлять его в качестве пода.

**Comment by milkyhack** [comment]
Добрый день , пытаюсь собрать ваш проект , тоже застрял на этой ошибке, а можно поподробней решение/

**Comment by RadiationX** [comment]
Так выше же есть ответ
