### ISSUE TITLE
Не все тайтлы отображаються

### ISSUE THREAD

**Issue by 1Maaayyy1** [anilibria/anilibria-ios#11]
В приложении не все тайтлы отображаются.(если это баг иммено на ios, тогда ладно)

**Comment by Allui** [comment]
@1Maaayyy1 
В приложении не отображаются заблокированные в РФ тайтлы

**Comment by 1Maaayyy1** [comment]
А обойти это нельзя?

**Comment by Allui** [comment]
@1Maaayyy1 
О каких тайтлах речь?

**Comment by 1Maaayyy1** [comment]
Бригада пожарных(1 сезон)
Внук мудреца 
И ещё те которые запрещены на территории рф, но  на сайте есть

**Comment by Allui** [comment]
@1Maaayyy1 
К сожалению у меня пока нет времени с этим разбираться.
Лучше отправь вопрос в телеграмме [Техподдержка AniLibria](https://t.me/Libria911Bot)
