### ISSUE TITLE
Ошибка при сборке приложения

### ISSUE THREAD

**Issue by z1row** [anilibria/anilibria-ios#16]
Пытаюсь собрать ваше приложение но получаю ошибку "Pods-Anilibria.debug.xcconfig" не найден. 
![image](https://user-images.githubusercontent.com/79547153/224310300-3a17f477-8600-4a8d-8f50-5d581a76f367.png)

**Comment by Allui** [comment]
@z1row вы установили поды?

**Comment by z1row** [comment]
Как это сделать?

**Comment by Allui** [comment]
@z1row 
[cocoapods](https://cocoapods.org/)
