### ISSUE TITLE
English support

### ISSUE THREAD

**Issue by TomerGamerTV** [anilibria/anilibria-ios#18]
Can you add support for English text? I wanted to try translating the app myself but I'm having trouble building it...

**Comment by Allui** [comment]
Hi @TomerGamerTV 
I don’t see the point in supporting English now, because there is only Russian-language content...

**Comment by TomerGamerTV** [comment]
I understand Russian but can’t read it. Having English text would really help people like me, I can even translate it if you don’t have the time to do it just tell me how and I will send you a pull request or something like that.

**Comment by Allui** [comment]
@TomerGamerTV 
Fair point. I'll try to add english once I have time

**Comment by TomerGamerTV** [comment]
Thanks 🙏, do you need any help? Maybe I could translate other parts of anilibria too (like their desktop programs or website)

**Comment by Allui** [comment]
I'll reach you if I need help

**Comment by TomerGamerTV** [comment]
> I'll reach you if I need help

👍🏻

**Comment by TomerGamerTV** [comment]
Thanks! This is exactly what I wanted, do you know if it's possible to add translation to the website/server? I can help with that if needed.

**Comment by Allui** [comment]
> Thanks! This is exactly what I wanted, do you know if it's possible to add translation to the website/server? I can help with that if needed.

@TomerGamerTV It would be better if you ask about it in telegram - tg://resolve?domain=Libria911Bot
