### ISSUE TITLE
Возможно ли с вами связаться?

### ISSUE THREAD

**Issue by Leeksov** [anilibria/anilibria-ios#23]
Хотел бы предложить помощь в написание тёмной темы для приложения

Можете связаться со мной?
t.me/leeksov

**Comment by TheTokyoGuy** [comment]
Очень хорошая идея!

**Comment by Leeksov** [comment]
> Очень хорошая идея!

Отпишите мне? На гите не очень удобно общаться))

**Comment by Allui** [comment]
@Leeksov  Никто не запрещает заняться разработкой темной темы. Вы спокойно можете сделать форк и потом отправить пуллреквест в наш репозиторий.
