### ISSUE TITLE
Скачивание через Scarlet

### ISSUE THREAD

**Issue by Teyni** [anilibria/anilibria-ios#28]
При скачивании через Скарлетт выдает ошибку: пример приведен на фото ![image](https://github.com/user-attachments/assets/a0405550-8ed5-4ec0-9f54-c91e69340c7c)

**Comment by Allui** [comment]
Ну тут ничего не поделать. В Apple стор приложение не пропускают, а отвечать за работоспособность приложения при установке со сторонних источников я не могу. Я проверяю только установку приложения с помощью AltStore. Но и при его использовании я не могу гарантировать работоспособность.
