### ISSUE TITLE
Отсутствие некоторых тайтлов

### ISSUE THREAD

**Issue by ukich-hubber** [anilibria/anilibria-ios#30]
Заметил что некоторых тайтлов нет в приложении, хотя на оф сайте они имеются, как я понимаю это сделано намеренно, но интересует вопрос для чего это сделано?

**Comment by Allui** [comment]
В целом это не ко мне вопрос. Тут лучше писать в тех поддержку.
Но на сколько знаю, скрываются в основном только тайтлы на которые жаловались правообладатели.
Дополнительно локально ничего не скрываю, все регулируется сервером.
