### ISSUE TITLE
Список серий у тайтла

### ISSUE THREAD

**Issue by CrazyHackGUT** [anilibria/anilibria-ios#4]
Просьба добавить возможность открывать полный список серий у тайтла перед просмотром. На многосерийных тайтлах (по типу того же Боруто) не очень удобно при первом открытии бить пальцем по стрелочке вправо, чтобы долистать до последней серии, которую и нужно просмотреть.

**Comment by Allui** [comment]
https://user-images.githubusercontent.com/10290335/128889967-f81719e5-29a6-41da-9575-718b91334f7c.MP4

**Comment by Allui** [comment]
Полный список серий отображается при нажатие на номер серии как показано на ролике выше.
